### ISSUE TITLE
spotify code?

### ISSUE THREAD

**Issue by DRTXY1** [ZombieBro2044/discord-custom-rpc-and-with-button#1]
how do i get that spotify code? 

spotify:XXX

**Comment by ZombieBro2044** [comment]
Step 1 go to webplayer in Spotify

https://open.spotify.com

Then choose whatever song you like click and hold the image for 3 sec! And select open in new tab!

![IMG_20220408_062609](https://user-images.githubusercontent.com/77621560/162342700-3175b8ff-c3d6-4dc9-ac70-8e1f11f2138e.jpg)

Then it would be open in a new tab and click on it's url.
![IMG_20220408_062731](https://user-images.githubusercontent.com/77621560/162342753-91a0988d-52fb-469f-babc-0b1b78dc9302.jpg)

Copy the code after `image/`
![IMG_20220408_062636](https://user-images.githubusercontent.com/77621560/162342845-768c4a91-189b-476f-9656-7df3dafc2608.jpg)

Hope it would help 👍

**Comment by ZombieBro2044** [comment]
Make sure you choose image from a album or a playlist to make it worked!
